[shell]
program = "/bin/zsh"
args = [ "-l", "-c", "tmux" ]

[window]
dynamic_padding = false
decorations = "None"
opacity = 0.9

  [window.padding]
  x = 3
  y = 0

  [window.class]
  instance = "Alacritty"
  general = "Alacritty"


[scrolling]
history = 5000
multiplier = 3

[font]
size = 11

  [font.normal]
  family = "Iosevka Nerd Font"
  style = "Regular"

  [font.bold]
  family = "Iosevka Nerd Font"
  style = "Bold"

  [font.italic]
  family = "Iosevka Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "Iosevka Nerd Font"
  style = "Bold Italic"

  [font.offset]
  x = 0
  y = 0


[selection]
save_to_clipboard = false

# Keybindings

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "F11"
mods = "None"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Paste"
mods = "None"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
mods = "None"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "None"
action = "ScrollPageUp"
mode = "~Alt"

[[keyboard.bindings]]
key = "PageDown"
mods = "None"
action = "ScrollPageDown"
mode = "~Alt"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"
mode = "~Alt"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"
mode = "~Alt"

# Themes

# TokyoNight Colors

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[colors.normal]
black = "0x15161e"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xa9b1d6"

[colors.bright]
black = "0x414868"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xc0caf5"

[[colors.indexed_colors]]
index = 16
color = "0xff9e64"

[[colors.indexed_colors]]
index = 17
color = "0xdb4b4b"
