[default]
duration = "30m"
mode = "stretch"
sorting = "random"

# Wallpapers from the following source:
# https://github.com/identityapproved/nightwallpapers
[any]
path = "/home/identityapproved/git/nightwallpapers/papers"

[DVI-D-1]
mode = "center"
