[default]
duration = "30m"
mode = "stretch"
sorting = "random"

# Wallpapers from the following source:
# https://github.com/D3Ext/aesthetic-wallpapers
[any]
path = "/home/identityapproved/git/aesthetic-wallpapers/images"

[DVI-D-1]
mode = "center"
